### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by thaneb** [paxman/LEDE-OpenWRT-firmware-for-WRT350n-v2#1]
I'm going to try install your "LEDE Reboot SNAPSHOT r5142-20d363a" on my wrt350n, sounds greats, do you have any recommendations regarding to this test to come ?
i hope to be able to finally use my wrt350n (10 years after buying it... a decade to take the dust) as wireless to ethernet bridge with a open-vpn client (i hope being able to use the on box button to connect/disconnet the vpn)...
Do you own a wrt350n by yourself to have such interest in this old box ?
anyway, many thanks for your work on it !

**Comment by paxman** [comment]
Hi, 
thank you for your kind words, I really appreciate it!

You are correct, I do own a wrt350n v2 and am using it as a wireless repeater (precisely because, AFAICR, original manufacturer's firmware did not have this option).

I'm not sure what test are you referring to, could you be more specific?

Note that the firmwares aren't built with any of the VPN supported packages (only Luci and relayd are built ) simply because I have no use of these packages and it also would take way too long to compile.

Kind regards,
paxman

**Comment by thaneb** [comment]
I was referring to the install and use of your compiled firmware (my wrt350n stayed bricked for many years after a standard 10.03 openwrt flash)..
I really need to go ahead into the openwrt/LEDE building for my wrt350n, I'm digging on the lede project, but i'm unable to find the orion source or "r5142" links, could you please give me a clue to find sources to download for building my own wrt350n firmware ? (if only it could be possible that orion came back to the official trunk/branch..)..

Best regards,
thaneb

**Comment by thaneb** [comment]
ho, i think i finally find the start point ^^ https://git.lede-project.org/?p=source.git;a=shortlog;h=refs/tags/v17.01.4 really boring that this arch isn't officially supported..

**Comment by paxman** [comment]
Hi,
sorry for the late reply.

> I was referring to the install and use of your compiled firmware (my wrt350n stayed bricked for many years after a standard 10.03 openwrt flash)..

If your device is bricked you can use the so called "Download mode" flash method as described [here](http://wiki.openwrt.org/toh/linksys/wrt350nv2#download_mode).
Otherwise use the "-sysupgrade.img" ending file for updating via browser in the device's web admin GUI.

> I really need to go ahead into the openwrt/LEDE building for my wrt350n, I'm digging on the lede project, but i'm unable to find the orion source or "r5142" links,

The second number in "r5142-20d363a" link is the start of the source commit hash, in this instance https://github.com/lede-project/source/commit/20d363aed395e07ff42fe648f898b17f2077cc82, that was compiled.
You can download LEDE repository up to a specific commit by git with [these commands](https://stackoverflow.com/a/14091182).

>  could you please give me a clue to find sources to download for building my own wrt350n firmware ? (if only it could be possible that orion came back to the official trunk/branch..)..

> ho, i think i finally find the start point ^^ https://git.lede-project.org/?
p=source.git;a=shortlog;h=refs/tags/v17.01.4 really boring that this arch isn't officially supported..
OpenWRT/LEDE source is the same for all devices, you must just configure which firmware you want to compile - I trust you are familiar with [the official](https://lede-project.org/docs/guide-developer/install-buildsystem) [build system](https://lede-project.org/docs/guide-developer/use-buildsystem) documentation?

The problem with WRT350N v2 is that you cannot select it as a target in menuconfig as it is [marked as broken](https://github.com/lede-project/source/commit/a4d7571367920e7e31f60d9c4c23a1eed4d659c7).
Because of this it doesn't show in the menu. To make it selectable, you can enable "Show broken platforms / packages" option under "Advanced configuration options (for developers)" menu.

Kind regards,
paxman

**Comment by thaneb** [comment]
Hello Paxman, 
I finally have few days free to have a serious look to lede building, and so, sorry, I will bother you little bit (I still would like to being able to build and install others app (openvpn, usb storage, 4G usb modem etc etc))...
i followed instruction from openwrt wiki to create a openwrt source folder in my ubuntu vb's desktop, successfully build a first openwrt-ar71xx-tiny-tl-mr3020-v1-squashfs-sysupgrade.bin to test that I have everything working well (I choose the mr3020 because i know it's a small build for a small storage router, I own one and must use extroot to install all what i needed on it).
Now i use the git clone https://github.com/paxman/LEDE-OpenWRT-firmware-for-WRT350n-v2.git command to download your branchinto another folder..
The next step is to use files from your branch to replace the ones in the the main Lede/openwrt trunk folder ? (simply copy/past files from your branch folder to replace the one in the lede trunk ?)
I had a look to the link you gave me before, but I'm not sure to understand it well..
ben

**Comment by ValCher1961** [comment]
Hi Paxman!
Oh, I'm glad that there is someone else who has not forgotten and left an old wrt350nv2! I already thought that I was the only one left with someone else alive wrt350n. True, I do not use it constantly, and from case to case for experiments. Several times he already experienced a clinical death, but every time after the resurrection he pleased me with his new opportunities. Now it is already very different from the factory one, it has increased memory to 128mb, a new Atheros AR9280 wi-fi card is installed and Debian Stretch is installed on the SSD.

**Comment by paxman** [comment]
> Now i use the git clone https://github.com/paxman/LEDE-OpenWRT-firmware-for-WRT350n-v2.git command to download your branchinto another folder..
> The next step is to use files from your branch to replace the ones in the the main Lede/openwrt trunk folder ? (simply copy/past files from your branch folder to replace the one in the lede trunk ?)

Yes, you can either replace .config file with the ones from releases in this repository, or use a .config "seed" [(see build HOWTO)](https://openwrt.org/docs/guide-developer/build-system/use-buildsystem#configure_using_config_diff_file); these seed files are located under "[release folder]/targets/orion/generic/config.{seed or buildinfo}" ([latest release example](https://github.com/paxman/LEDE-OpenWRT-firmware-for-WRT350n-v2/blob/master/r10969-869a0183b9%20WSL%20no%20ipv6%20no%20odhcpd/targets/orion/generic/config.buildinfo)).
Replacing Makefile is not really necessary.

**Comment by ValCher1961** [comment]
@paxman.
I made a patch to build a 4.14.X kernel based on Device Tree for wrt350nv2.
Would you be interested in applying it?

**Comment by thaneb** [comment]
@ValCher1961, is there any place we could see your work on the unloved wrt350n v2?

**Comment by ValCher1961** [comment]
I wouldn't want to create a new repo, but I can lay out a patch here if not against the host.

**Comment by ValCher1961** [comment]
Only in the flash@0 section you need to change the sections as it was on the stock.
I'm going to fix it now.

Updated - https://yadi.sk/d/2otxji4tSPeL8w

Check out the nor-flash sections used in Openwrt?

**Comment by paxman** [comment]
Nice work ValCher1961!

For stock device, there's no need for such compilation. In the [target Makefile](https://github.com/openwrt/openwrt/blob/master/target/linux/orion/Makefile) set KERNEL_PATCHVER  to 4.14 and create patches (patches-4.14 directory, if any; in this case DT definitions) and default .config (.config-4.14). I believe I've done this once, but kernel was just too big for current partition size.

I like to have a simple, (somewhat) user friendly solutions, so for your 128mb mod, I'd like to have it as a menuconfig option, since not everybody would like to use Debian rootfs, and OpenWRT's build system is well integrated. I wanted to fork it, and split devices (WNR845T, ...) in makefiles, however...

Sadly, while porting netconsole to routers' u-boot, I have bricked it; not even download mode works.
This means even bootloader is beyond repair; which means the only way to unbrick it is JTAG. but, I see that USB JTAG dongles are priced ~30€+, which is in the ballpark of a new router. For just one time usage and for device almost 10 years old it is just not worth it. Besides, my soldering skills are basically nonexistent.
I will post the netconsole changes - it's basically a copy from [pepe2k's mod](https://github.com/pepe2k/u-boot_mod) - (without the code that bricks it, ofcourse), should anyone want to try it, but other than that I don't think I will update this repository anymore.

It' been fun 10 years, but sometimes you just have to move on.

**Comment by ValCher1961** [comment]
@paxman, Thanks for the answer.
Yes, I understand you, buying for an old JTAG device for that kind of money and for one-time use ... I think it's not worth it. I sympathize with you and believe in miracles.
Our router, of course, is hopelessly outdated, but in its architecture there are devices such as a switch and crypto-CESA, which puts it on the same line with modern functionality. On it, I test these blocks as on wrt3200acm with Debian (McDebian).
Regarding the publication of KERNEL_PATCHVER on github, I don’t know very well how to do this, but if it’s not difficult for you, you can do it yourself.
In the last patch, I fixed the operation of the LEDs of network devices (Lan1, Lan2, Lan3, Lan4, WAN), now they show the connection speed on the drain (green - 100mbit, yellow - 1000mbit), I2C bus support is added, it is possible to control the temperature of the Switch on it -88e6131.
Regarding the .config file, as I understand it, you need a basic kernel configuration with basic functions so that the kernel can enter the stock size of the partition (0x0 - 0x001a0000), yes? If, yes, I will try to introduce such a configuration file.

**Comment by paxman** [comment]
> @paxman, Thanks for the answer.
> Yes, I understand you, buying for an old JTAG device for that kind of money and for one-time use ...I think it's not worth it. I sympathize with you and believe in miracles.

Well, there is one ~45€ "new" (unopened, foil and all) on ebay...

> Our router, of course, is hopelessly outdated, but in its architecture there are devices such as a > switch and crypto-CESA, which puts it on the same line with modern functionality. On it, I test these blocks as on wrt3200acm with Debian (McDebian).

Yes, these are nice perks to have, but to be honest, that they're on par with todays devices is, I think, because these functions haven't seen so much development as other areas - which WRT350n is lacking in - have (newer wireless standards, more powerful SoC's, efficient power consumption)   and/or there was/is no incentives to upgade them (we still rarely have access to 1gbit internet to fully use eth ports). The architecture is also slowly [losing support](https://www.phoronix.com/scan.php?page=news_item&px=GCC-9-Dropping-Older-ARM).

> Regarding the publication of KERNEL_PATCHVER on github, I don’t know very well how to do this, but if it’s not difficult for you, you can do it yourself.

I'll probably do it as a branch and put it in master Readme.

> In the last patch, I fixed the operation of the LEDs of network devices (Lan1, Lan2, Lan3, Lan4, WAN), now they show the connection speed on the drain (green - 100mbit, yellow - 1000mbit), I2C bus support is added, it is possible to control the temperature of the Switch on it -88e6131.

Great work!

> Regarding the .config file, as I understand it, you need a basic kernel configuration with basic functions so that the kernel can enter the stock size of the partition (0x0 - 0x001a0000), yes? If, yes, I will try to introduce such a configuration file.

Yes, except 4.9 kernel uses [slightly smaller partition](https://github.com/openwrt/openwrt/blob/master/target/linux/orion/patches-4.9/100-wrt350nv2_openwrt_partition_map.patch).


Oh, I forgot to ask; what chip did you use for your RAM upgrade? 
And which AR9280 wifi card? (I couldn't find any with mini PCI interface)

**Comment by ValCher1961** [comment]
@paxman 
I installed the MikroTik R52Hn card, it has already been withdrawn from production. Now MikroTik has an mini-PCI R52HnD card, which is expensive - $59.

To upgrade memory to 128MB, you need to use 512MB chips with 16 bit tires - 512MB (32Mx16), TSOP-II Package (66pin)
For example:
EM6AB160TSH - http://www.etron.com/manager/uploads/EM6AB160TSH&WKH_Rev%201.0.pdf
HY5DU12622BT - https://www.skhynix.com/product/filedata/fileDownload.do?seq=4218

I installed the NCP NP25D3216512K-5 chips, but unfortunately I can't find a data sheet anywhere on them.
Chips can be removed from old PC memory cards, it seems they have been named - SDRAM DIMM, SDRAM SO-DIMM.
The main thing is that they meet the necessary characteristics - 512Mb(32Mx16), VDD/VDDQ = 2.5V, SSTL_2 I/O Interface, 66 Pin TSOP II, 0.65mm pin pitch, Clock speed (not lower) - 200 MHz (memory controller we have 166 MHz)

**Comment by ValCher1961** [comment]
@paxman Excuse me, I misled you with the ar9280 card. I bought the card a long time ago, and forgot what chip it is on. Now looked at the Mikrotik website, it turns out to be on the chip ar9220.
Why I called it ar9280, because in dmesg it is displayed as AR9280.
![AR9280](https://user-images.githubusercontent.com/17226948/66650633-be35d200-ec39-11e9-9f70-0c5a0e81076d.JPG)
Again, I'm sorry.

**Comment by thaneb** [comment]
I may come back home (europe) for christmas, i will have a look if i still have the home made jtag - serial cable i made 12 years ago (for unbrick a wrt54gs), if i can find it in my hardware archives (understand if my mother didn't trash it^^) i could send it to you!!

**Comment by thaneb** [comment]
> I may come back home (europe) for christmas, i will have a look if i still have the home made jtag - serial cable i made 12 years ago (for unbrick a wrt54gs), if i can find it in my hardware archives (understand if my mother didn't trash it^^) i could send it to you!!

Hello Paxman, so sorry to not updated you before.. our european trip was aborted so I still don't know if my jtag cable is still waiting somewhere or if it is already trashed in another galaxy.. :-/
I started to really dig into the openwrt compiling... I need to build a vpn client bridge with the wrt350nv2, so its ethernet/wifi clients will be relocated to france (in order to easily access VOD services). I forked the 18.06 openwrt (as the orion platform has been kicked off from openwrt last january, the 19.xx removed it from the unsupported list) and use one version of your patch.
https://github.com/thaneb/openwrt-18.06-for-wrt350n-v2
I can compile it, many thanks to your work and advices, but I'm still yet unable to configure the wan port (every time i populate the /etc/config/network with a wan interface, in the best case it says the device isn't present, in the worst I have to flash the router again with the uboot)... but I will continue to investigate and test this.
I am curious about your netconsole port, and why not request a wrt350n v2 uboot update of pepe2k ? (last thing i saw about netconsole are 10 years old, thereas pepe2k are "only" 4-5 years old)
I upgraded the mini pci wifi with the card of a unused airport extreme 1st generation ( https://deviwiki.com/wiki/Apple_AirPort_Extreme_Base_Station_A1143_(MA073LL/A) ), it's providing a  Atheros couple AR5416/AR5133 abgn 3x3:2 instead of the older AR5416/AR2133 (no a 5Ghz wifi), it looks to be more stable... 
The pepe2k's uboot upgrade could be interesting to maybe upgrade the flash chip (always the same useless airport extreme which could offer a 16Mg chip fully compatible, as this router use exactly the same marvell orion arm5v cpu), i hoped i could also took it's 64Mg ram, but it isn't a 64Gb chip, it's a 2 x 32Mg couple.. so I should look for the old laptop sdram that should still be somewhere at my family house (maybe with the jtag cable..)
Could you put your uboot work files somewhere ?
I will try to motivate my stepfather to dig into my stuff boxes to check if he can find this cable .. and if he can find it, I will make him send it to you by post !

**Comment by thaneb** [comment]
> I will post the netconsole changes - it's basically a copy from [pepe2k's mod](https://github.com/pepe2k/u-boot_mod) - (without the code that bricks it, ofcourse), should anyone want to try it, but other than that I don't think I will update this repository anymore.

@paxman can you provide me with this upgrade and its source ? it's my turn to brick the wrt350n ^^
